//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace ABLParser.Progress.Xref
{
    using System.Xml.Serialization;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "uri:schemas-progress-com:XREFD:0005")]
    [System.Xml.Serialization.XmlRootAttribute("Cross-reference", Namespace = "uri:schemas-progress-com:XREFD:0005", IsNullable = false)]
    public partial class Crossreference
    {

        private CrossreferenceSource[] sourceField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Source")]
        public CrossreferenceSource[] Source
        {
            get
            {
                return this.sourceField;
            }
            set
            {
                this.sourceField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "uri:schemas-progress-com:XREFD:0005")]
    public partial class CrossreferenceSource
    {

        private string sourceguidField;

        private System.Nullable<int> filenumField;

        private CrossreferenceSourceReference[] referenceField;

        private string filenameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Source-guid", IsNullable = true)]
        public string Sourceguid
        {
            get
            {
                return this.sourceguidField;
            }
            set
            {
                this.sourceguidField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("File-num", IsNullable = true)]
        public System.Nullable<int> Filenum
        {
            get
            {
                return this.filenumField;
            }
            set
            {
                this.filenumField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Reference")]
        public CrossreferenceSourceReference[] Reference
        {
            get
            {
                return this.referenceField;
            }
            set
            {
                this.referenceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("File-name")]
        public string Filename
        {
            get
            {
                return this.filenameField;
            }
            set
            {
                this.filenameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "uri:schemas-progress-com:XREFD:0005")]
    public partial class CrossreferenceSourceReference
    {

        private string sourceguidField;

        private System.Nullable<int> filenumField;

        private System.Nullable<int> refseqField;

        private System.Nullable<int> linenumField;

        private string objectcontextField;

        private string accessmodeField;

        private string datamemberrefField;

        private string temprefField;

        private string detailField;

        private System.Nullable<bool> isstaticField;

        private System.Nullable<bool> isabstractField;

        private CrossreferenceSourceReferenceClassref[] classrefField;

        private CrossreferenceSourceReferenceStringref[] stringrefField;

        private CrossreferenceSourceReferenceParameterref[] parameterrefField;

        private CrossreferenceSourceReferenceDatasetref[] datasetrefField;

        private CrossreferenceSourceReferenceInterfaceref[] interfacerefField;

        private string referencetypeField;

        private string objectidentifierField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Source-guid", IsNullable = true)]
        public string Sourceguid
        {
            get
            {
                return this.sourceguidField;
            }
            set
            {
                this.sourceguidField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("File-num", IsNullable = true)]
        public System.Nullable<int> Filenum
        {
            get
            {
                return this.filenumField;
            }
            set
            {
                this.filenumField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Ref-seq", IsNullable = true)]
        public System.Nullable<int> Refseq
        {
            get
            {
                return this.refseqField;
            }
            set
            {
                this.refseqField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Line-num", IsNullable = true)]
        public System.Nullable<int> Linenum
        {
            get
            {
                return this.linenumField;
            }
            set
            {
                this.linenumField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Object-context", IsNullable = true)]
        public string Objectcontext
        {
            get
            {
                return this.objectcontextField;
            }
            set
            {
                this.objectcontextField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Access-mode", IsNullable = true)]
        public string Accessmode
        {
            get
            {
                return this.accessmodeField;
            }
            set
            {
                this.accessmodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Data-member-ref", IsNullable = true)]
        public string Datamemberref
        {
            get
            {
                return this.datamemberrefField;
            }
            set
            {
                this.datamemberrefField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Temp-ref", IsNullable = true)]
        public string Tempref
        {
            get
            {
                return this.temprefField;
            }
            set
            {
                this.temprefField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Detail
        {
            get
            {
                return this.detailField;
            }
            set
            {
                this.detailField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Is-static", IsNullable = true)]
        public System.Nullable<bool> Isstatic
        {
            get
            {
                return this.isstaticField;
            }
            set
            {
                this.isstaticField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Is-abstract", IsNullable = true)]
        public System.Nullable<bool> Isabstract
        {
            get
            {
                return this.isabstractField;
            }
            set
            {
                this.isabstractField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Class-ref")]
        public CrossreferenceSourceReferenceClassref[] Classref
        {
            get
            {
                return this.classrefField;
            }
            set
            {
                this.classrefField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("String-ref")]
        public CrossreferenceSourceReferenceStringref[] Stringref
        {
            get
            {
                return this.stringrefField;
            }
            set
            {
                this.stringrefField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Parameter-ref")]
        public CrossreferenceSourceReferenceParameterref[] Parameterref
        {
            get
            {
                return this.parameterrefField;
            }
            set
            {
                this.parameterrefField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Dataset-ref")]
        public CrossreferenceSourceReferenceDatasetref[] Datasetref
        {
            get
            {
                return this.datasetrefField;
            }
            set
            {
                this.datasetrefField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Interface-ref")]
        public CrossreferenceSourceReferenceInterfaceref[] Interfaceref
        {
            get
            {
                return this.interfacerefField;
            }
            set
            {
                this.interfacerefField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("Reference-type")]
        public string Referencetype
        {
            get
            {
                return this.referencetypeField;
            }
            set
            {
                this.referencetypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("Object-identifier")]
        public string Objectidentifier
        {
            get
            {
                return this.objectidentifierField;
            }
            set
            {
                this.objectidentifierField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "uri:schemas-progress-com:XREFD:0005")]
    public partial class CrossreferenceSourceReferenceClassref
    {

        private string sourceguidField;

        private System.Nullable<int> refseqField;

        private string inheritedlistField;

        private string implementslistField;

        private System.Nullable<bool> hasusepoolField;

        private System.Nullable<bool> isfinalField;

        private System.Nullable<bool> isserializableField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Source-guid", IsNullable = true)]
        public string Sourceguid
        {
            get
            {
                return this.sourceguidField;
            }
            set
            {
                this.sourceguidField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Ref-seq", IsNullable = true)]
        public System.Nullable<int> Refseq
        {
            get
            {
                return this.refseqField;
            }
            set
            {
                this.refseqField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Inherited-list", IsNullable = true)]
        public string Inheritedlist
        {
            get
            {
                return this.inheritedlistField;
            }
            set
            {
                this.inheritedlistField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Implements-list", IsNullable = true)]
        public string Implementslist
        {
            get
            {
                return this.implementslistField;
            }
            set
            {
                this.implementslistField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Has-use-pool", IsNullable = true)]
        public System.Nullable<bool> Hasusepool
        {
            get
            {
                return this.hasusepoolField;
            }
            set
            {
                this.hasusepoolField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Is-final", IsNullable = true)]
        public System.Nullable<bool> Isfinal
        {
            get
            {
                return this.isfinalField;
            }
            set
            {
                this.isfinalField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Is-serializable", IsNullable = true)]
        public System.Nullable<bool> Isserializable
        {
            get
            {
                return this.isserializableField;
            }
            set
            {
                this.isserializableField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "uri:schemas-progress-com:XREFD:0005")]
    public partial class CrossreferenceSourceReferenceStringref
    {

        private string sourceguidField;

        private System.Nullable<int> refseqField;

        private System.Nullable<int> maxlengthField;

        private string justificationField;

        private System.Nullable<bool> translatableField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Source-guid", IsNullable = true)]
        public string Sourceguid
        {
            get
            {
                return this.sourceguidField;
            }
            set
            {
                this.sourceguidField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Ref-seq", IsNullable = true)]
        public System.Nullable<int> Refseq
        {
            get
            {
                return this.refseqField;
            }
            set
            {
                this.refseqField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Max-length", IsNullable = true)]
        public System.Nullable<int> Maxlength
        {
            get
            {
                return this.maxlengthField;
            }
            set
            {
                this.maxlengthField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Justification
        {
            get
            {
                return this.justificationField;
            }
            set
            {
                this.justificationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<bool> Translatable
        {
            get
            {
                return this.translatableField;
            }
            set
            {
                this.translatableField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "uri:schemas-progress-com:XREFD:0005")]
    public partial class CrossreferenceSourceReferenceParameterref
    {

        private string sourceguidField;

        private System.Nullable<int> refseqField;

        private System.Nullable<int> dimensionField;

        private System.Nullable<bool> isappendField;

        private string datasetguidField;

        private int orderField;

        private bool orderFieldSpecified;

        private string parametermodeField;

        private string parameternameField;

        private string parametertypeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Source-guid", IsNullable = true)]
        public string Sourceguid
        {
            get
            {
                return this.sourceguidField;
            }
            set
            {
                this.sourceguidField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Ref-seq", IsNullable = true)]
        public System.Nullable<int> Refseq
        {
            get
            {
                return this.refseqField;
            }
            set
            {
                this.refseqField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> Dimension
        {
            get
            {
                return this.dimensionField;
            }
            set
            {
                this.dimensionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Is-append", IsNullable = true)]
        public System.Nullable<bool> Isappend
        {
            get
            {
                return this.isappendField;
            }
            set
            {
                this.isappendField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Dataset-guid", IsNullable = true)]
        public string Datasetguid
        {
            get
            {
                return this.datasetguidField;
            }
            set
            {
                this.datasetguidField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Order
        {
            get
            {
                return this.orderField;
            }
            set
            {
                this.orderField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OrderSpecified
        {
            get
            {
                return this.orderFieldSpecified;
            }
            set
            {
                this.orderFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("Parameter-mode")]
        public string Parametermode
        {
            get
            {
                return this.parametermodeField;
            }
            set
            {
                this.parametermodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("Parameter-name")]
        public string Parametername
        {
            get
            {
                return this.parameternameField;
            }
            set
            {
                this.parameternameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("Parameter-type")]
        public string Parametertype
        {
            get
            {
                return this.parametertypeField;
            }
            set
            {
                this.parametertypeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "uri:schemas-progress-com:XREFD:0005")]
    public partial class CrossreferenceSourceReferenceDatasetref
    {

        private string sourceguidField;

        private string datasetguidField;

        private System.Nullable<int> refseqField;

        private string nuriField;

        private string nprefixField;

        private System.Nullable<bool> isreferenceField;

        private string bufferlistField;

        private System.Nullable<int> datalinksField;

        private CrossreferenceSourceReferenceDatasetrefRelation[] relationField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Source-guid", IsNullable = true)]
        public string Sourceguid
        {
            get
            {
                return this.sourceguidField;
            }
            set
            {
                this.sourceguidField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Dataset-guid", IsNullable = true)]
        public string Datasetguid
        {
            get
            {
                return this.datasetguidField;
            }
            set
            {
                this.datasetguidField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Ref-seq", IsNullable = true)]
        public System.Nullable<int> Refseq
        {
            get
            {
                return this.refseqField;
            }
            set
            {
                this.refseqField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("N-uri", IsNullable = true)]
        public string Nuri
        {
            get
            {
                return this.nuriField;
            }
            set
            {
                this.nuriField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("N-prefix", IsNullable = true)]
        public string Nprefix
        {
            get
            {
                return this.nprefixField;
            }
            set
            {
                this.nprefixField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Is-reference", IsNullable = true)]
        public System.Nullable<bool> Isreference
        {
            get
            {
                return this.isreferenceField;
            }
            set
            {
                this.isreferenceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Buffer-list", IsNullable = true)]
        public string Bufferlist
        {
            get
            {
                return this.bufferlistField;
            }
            set
            {
                this.bufferlistField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Data-links", IsNullable = true)]
        public System.Nullable<int> Datalinks
        {
            get
            {
                return this.datalinksField;
            }
            set
            {
                this.datalinksField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Relation")]
        public CrossreferenceSourceReferenceDatasetrefRelation[] Relation
        {
            get
            {
                return this.relationField;
            }
            set
            {
                this.relationField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "uri:schemas-progress-com:XREFD:0005")]
    public partial class CrossreferenceSourceReferenceDatasetrefRelation
    {

        private string sourceguidField;

        private string datasetguidField;

        private string parentbuffernameField;

        private string childbuffernameField;

        private string relationlistField;

        private string relationnameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Source-guid", IsNullable = true)]
        public string Sourceguid
        {
            get
            {
                return this.sourceguidField;
            }
            set
            {
                this.sourceguidField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Dataset-guid", IsNullable = true)]
        public string Datasetguid
        {
            get
            {
                return this.datasetguidField;
            }
            set
            {
                this.datasetguidField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Parent-buffer-name", IsNullable = true)]
        public string Parentbuffername
        {
            get
            {
                return this.parentbuffernameField;
            }
            set
            {
                this.parentbuffernameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Child-buffer-name", IsNullable = true)]
        public string Childbuffername
        {
            get
            {
                return this.childbuffernameField;
            }
            set
            {
                this.childbuffernameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Relation-list", IsNullable = true)]
        public string Relationlist
        {
            get
            {
                return this.relationlistField;
            }
            set
            {
                this.relationlistField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("Relation-name")]
        public string Relationname
        {
            get
            {
                return this.relationnameField;
            }
            set
            {
                this.relationnameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "uri:schemas-progress-com:XREFD:0005")]
    public partial class CrossreferenceSourceReferenceInterfaceref
    {

        private string sourceguidField;

        private System.Nullable<int> refseqField;

        private string inheritedlistField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Source-guid", IsNullable = true)]
        public string Sourceguid
        {
            get
            {
                return this.sourceguidField;
            }
            set
            {
                this.sourceguidField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Ref-seq", IsNullable = true)]
        public System.Nullable<int> Refseq
        {
            get
            {
                return this.refseqField;
            }
            set
            {
                this.refseqField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Inherited-list", IsNullable = true)]
        public string Inheritedlist
        {
            get
            {
                return this.inheritedlistField;
            }
            set
            {
                this.inheritedlistField = value;
            }
        }
    }
}
